import { useAtom } from "jotai";
import Head from "next/head";
import { ReactNode } from "react";
import Header from "../patials/Header";
import { themeAtom } from "~/atoms";
import { useLocalStorage } from "usehooks-ts";
import { useTheme } from "~/context/themeContext";
type Props = { children: ReactNode };

const MainLayout = ({ children }: Props) => {
  const [theme] = useTheme();

  return (
    <div className={`${theme}`}>
      {/* <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Header />

      <main className=" ">{children}</main>
    </div>
  );
};

export default MainLayout;
